#spring properties
spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  cipdb:
    url: jdbc:postgresql://localhost:5432/cipdb
    username: postgres
    password: 1qaz2wsx
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      initial-size: 15
      min-idle: 10
      max-total: 100
      test-on-borrow: true
      validation-query: select 1
      max-wait-millis: 5000
      max-conn-lifetime-millis: 3600000
  authdb:
    url: jdbc:postgresql://localhost:5432/authdb
    username: postgres
    password: 1qaz2wsx
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      initial-size: 15
      min-idle: 10
      max-total: 100
      test-on-borrow: true
      validation-query: select 1
      max-wait-millis: 5000
      max-conn-lifetime-millis: 3600000
  measurementdb:
    url: jdbc:postgresql://localhost:5432/measurementdb
    username: postgres
    password: 1qaz2wsx
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      initial-size: 15
      min-idle: 10
      max-total: 100
      test-on-borrow: true
      validation-query: select 1
      max-wait-millis: 5000
      max-conn-lifetime-millis: 3600000
  mysql:
    url: jdbc:mysql://localhost:3307/SynCare
    username: root
    password: 1qaz2wsx
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      initial-size: 15
      min-idle: 10
      max-total: 100
      test-on-borrow: true
      validation-query: select 1
      max-wait-millis: 5000
      max-conn-lifetime-millis: 3600000
#  profiles:
#    active: ttshb 
#liquibase
#liquibase:
#  change-log: classpath:/db/changelog/db.changelog-master.yml
#Customize zookeeper properties
#registry:
#  address:
#    - localhost:2181
#Customize redis
redis:
  host: localhost
  port: 6379
  pool:
    max-total: 100
    max-wait-millis: 5000
    min-idle: 10
    max-idle: 30
    test-on-borrow: true
#Customize solr
solr:
  url: http://localhost:8983/solr/syntron
#session timeout
session:
  timeout-sec: 2592000
#logger
logging:
#  file: ./logs
  level:
    ROOT: INFO
    com.syntrontech.cip: TRACE
    
#push service url
push-service:
  url: http://localhost:9002/push/message
